# Generated by Django 5.0.1 on 2024-02-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=100)),
                ('work_type', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
            ],
        ),
    ]
