# Generated by Django 5.0.1 on 2024-02-14 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_regmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regmodel',
            old_name='fname',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='regmodel',
            old_name='lname',
            new_name='heq',
        ),
        migrations.RenameField(
            model_name='regmodel',
            old_name='mname',
            new_name='number',
        ),
    ]
