# Generated by Django 5.0.1 on 2024-02-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_applyjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
