# Generated by Django 5.0.1 on 2024-02-26 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0006_alter_applyjob_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applyjob',
            old_name='uname',
            new_name='name',
        ),
    ]
