# Generated by Django 5.0.1 on 2024-02-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0007_rename_uname_applyjob_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyjob',
            name='experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
